title: Adepoju Temitope Elizabeth
description: Data Analyst | Relationship Officer | Turning Data into Insights and Impact
theme: jekyll-theme-minimal

social_links:
  linkedin: https://www.linkedin.com/in/temitopeadepoju
  github: https://github.com/temitopeadep
  email: ttemitope.adepoju@gmail.com 

footer: © 2025 Adepoju Temitope Elizabeth | Data Analytics Portfolio
